# Generated by Django 6.0.3 on 2026-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Switch JetStream 8 Portas Gigabit PoE+ com 2 Slots SFP', max_length=100)),
                ('categoria', models.CharField(choices=[('SWITCH', 'Switch de Rede'), ('Router', 'Roteador / Gateway'), ('AP', 'Access Point'), ('CONECTIVIDADE', 'Transceiver / SFP')], default='SWITCH', max_length=20)),
                ('gerenciamento', models.CharField(choices=[('L2', 'Layer 2 (Gerenciável)'), ('L3', 'Layer 3 (Gerenciável/Routing)'), ('UNMANAGED', 'Não Gerenciado (Plug-and-Play)'), ('SMART', 'Smart/Inteligent (Configuração Básica)')], default='L2', max_length=15)),
                ('velocidade_uplink', models.CharField(choices=[('1G', '1 Gbps (Standard)'), ('10G', '10 Gbps (SFP+)'), ('40G', '40 Gbps (QSFP+)'), ('100G', '100 Gbps (QSFP28)')], default='1G', max_length=10)),
                ('suporta_poe', models.BooleanField(default=False, verbose_name='Possui PoE?')),
                ('potencia_poe', models.PositiveIntegerField(blank=True, default=0, help_text='Potência total em Watts (ex: 370W)', null=True)),
                ('quantidade_portas', models.PositiveIntegerField(default=24)),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('estado', models.CharField(choices=[('ESTOQUE', 'Disponível em Estoque'), ('USO', 'Em Uso / Operação')], default='ESTOQUE', max_length=15)),
                ('local', models.CharField(default='Sede Piratininga', max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre VLANs, STP ou versão de Firmware', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
