# Generated by Django 6.0.3 on 2026-04-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_equipamento_cadastrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série'),
        ),
    ]
