# Generated by Django 6.0.3 on 2026-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_equipamento_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
